export const env = {
  databaseUrl: process.env.DATABASE_URL ?? "",
  nextAuthUrl: process.env.NEXTAUTH_URL ?? "http://localhost:3000",
  nextAuthSecret: process.env.NEXTAUTH_SECRET ?? "",
  aiServiceUrl: process.env.AI_SERVICE_URL ?? "http://localhost:8000",
  awsRegion: process.env.AWS_REGION ?? "us-east-1",
  awsAccessKeyId: process.env.AWS_ACCESS_KEY_ID ?? "",
  awsSecretAccessKey: process.env.AWS_SECRET_ACCESS_KEY ?? "",
  awsS3Bucket: process.env.AWS_S3_BUCKET ?? "",
  awsS3PublicBaseUrl: process.env.AWS_S3_PUBLIC_BASE_URL ?? "",
  sendGridApiKey: process.env.SENDGRID_API_KEY ?? "",
  sendGridFromEmail: process.env.SENDGRID_FROM_EMAIL ?? "noreply@example.com",
  twilioAccountSid: process.env.TWILIO_ACCOUNT_SID ?? "",
  twilioAuthToken: process.env.TWILIO_AUTH_TOKEN ?? "",
  twilioWhatsAppNumber: process.env.TWILIO_WHATSAPP_NUMBER ?? "",
  googleCalendarClientId: process.env.GOOGLE_CALENDAR_CLIENT_ID ?? "",
  googleCalendarClientSecret: process.env.GOOGLE_CALENDAR_CLIENT_SECRET ?? "",
  googleCalendarRefreshToken: process.env.GOOGLE_CALENDAR_REFRESH_TOKEN ?? "",
  outlookClientId: process.env.OUTLOOK_CLIENT_ID ?? "",
  outlookClientSecret: process.env.OUTLOOK_CLIENT_SECRET ?? "",
  outlookRefreshToken: process.env.OUTLOOK_REFRESH_TOKEN ?? "",
};
